languageCode = "en-us"
title = "Marcus Bowyer"
baseurl = "http://www.marcusbowyer.co.uk/"
theme = "dimension"

[params]
  title = "Marcus Bowyer"
  description = '<!--[-->hello<!--]--><br />
                <!--[-->my name is marcus<!--]-->'
  logo = "fa-terminal"
  copyright = "marcus bowyer"

[[params.social]]
  medium = "email"
  icon = "envelope"
  link = "mailto:marcus@marcusbowyer.co.uk"

[[params.social]]
  medium = "linkedin"
  icon = "linkedin"
  link = "http://linkedin.com/in/marcusbowyer"

[[params.social]]
  medium = "github"
  icon = "github"
  link = "http://github.com/marcusbooyah"
